steps:
- name: 'docker/compose'
  args: ['up', '-d']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcf-serv-vm/app-note']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'app-notes', '--image', 'gcr.io/gcf-serv-vm/app-note', '--region', 'us-central1', '--platform', 'managed', '--allow_unauthenticated']
images:
  - gcr.io/gcf-serv-vm/app-notes